### ISSUE TITLE
BigIntegerRandomizer only returns BigIntegers within the range of 32 bit integers

### ISSUE THREAD

**Issue by PascalSchumacher** [benas/random-beans#100]
As reported by @ashrko619 on gitter:

Currently BigIntegerRandomizer only returns BigIntegers within the range of 32 bit integers.

```java
public BigInteger getRandomValue() {
        return new BigInteger(valueOf(delegate.getRandomValue()));
    }
```

To have larger and more random values can we change the function to something like this ?

```java
public BigInteger getRandomValue() {
        BigInteger ret = BigInteger.valueOf(delegate.getRandomValue());
        int noOfMultipliers = delegate.getRandomValue() % 10;
        for (int i = 0; i < noOfMultipliers; ++i) {
            ret = ret.multiply(BigInteger.valueOf(delegate.getRandomValue()));
        }
        return ret;
    }
```

**Comment by benas** [comment]
Hi Pascal,

Thanks for creating this issue. We are sure to not forget it for next release :smile: 

@ashrko619 I'll keep you informed when the fix is merged in the master branch.

Regards
Mahmoud

**Comment by benas** [comment]
Hi @ashrko619

I've tried your snippet and it generates more random values indeed :+1: 

I was thinking about reusing the existing constructor `BigInteger(int numBits, Random r)` with larger number of bits and a source of randomness instead of creating a new logic with multipliers.

We have already the `AbstractRandomizer` which holds a `Random` instance. We can make the `BigIntegerRandomizer` extend this class and use the specified constructor:

```java
public class BigIntegerRandomizer extends AbstractRandomizer<BigInteger> {
    
    @Override
    public BigInteger getRandomValue() {
        return new BigInteger(128, random);
    }
}
```

This will generate 128 bits BigInteger (which is large enough IMO). The source of randomness will be delegated to the (inherited) `Random` instance which we can seed to get stable random values.

What do you think of this idea?

Kind regards
Mahmoud

**Comment by ashrko619** [comment]
Hi @benas,

I wasn't aware of this constructor in the BigInteger class. This method seems much better :+1: 

Regards,
Ashwin

**Comment by benas** [comment]
Hi @ashrko619 

The improvement has been implemented and merged in the master branch.

Regards
Mahmoud
