### ISSUE TITLE
Release 3.0?

### ISSUE THREAD

**Issue by PascalSchumacher** [benas/random-beans#125]
There have been a lot of improvements and bug-fixes since the 2.0 release.

As the saying goes "Release early, release often". Further improvements and fixes can always be released as 3.x/4.0 later on.

I think it's time for a release, what do you think?

**Comment by benas** [comment]
Hi, I was planning to release v3 next week, since I'll be on holidays :smile: 

> Release early, release often

Sure! v2 was released on Feb 19. IMO, it's not that late that a major version comes out 3 months later.
The problem is that I should have released minor versions 2.1, 2.2 .. in between. But I have focused on Java 8 support for v3 much a lot.

Anyway, it is often said that [the third time’s the charm](http://www.javaworld.com/article/2072651/becoming-a-great-programmer--use-your-trash-can.html). I hope this third attempt is the right one :smile: And if does, it is thanks to your great contributions, definitely.

**Comment by PascalSchumacher** [comment]
>I was planning to release v3 next week, since I'll be on holidays

Great, enjoy your holiday. :smile: 

>v2 was released on Feb 19. IMO, it's not that late that a major version comes out 3 months later.

Sure. You are right.

>And if does, it is thanks to your great contributions, definitely.

Thanks! My contributions are only a small part of random-beans. Most of the credit goes to you. :smile:
