### ISSUE TITLE
Not populating set of pojo

### ISSUE THREAD

**Issue by rishirane** [benas/random-beans#19]
I have a pojo named Transaction which contains Set of another pojo Accounts

```java
public class TransactionDTO{
      private Set<Accounts> accList;
      public void setAccList(Set<Accounts> accList){
           this.accList=accList;
      }
      public Set<Accounts> getAccList(){
           return accList;
      }
      .......
}

public class Account{
     private String acNo;
      .......
}

```
I am trying to populate TransactionDTO with Jpopulator.
It populates all values properly except Set values.

**Comment by benas** [comment]
Hi,

Thanks for pointing out this issue.

Populating collections is not supported in the current version, see here:

https://github.com/benas/jPopulator/wiki/Supported-types#arrays-and-collection-types

This is planned for the next release. Any contribution is welcome :-)

keep tuned.

Regards,
Mahmoud

**Comment by stephanrauh** [comment]
How do you plan to deal with type erasure and inheritance? jPopulator doesn't know which kind of object the `Set` contains, nor does it know which implementation of `Set` to chose. The latter could be solved by using a default implementation for each interface (`List` --> `ArrayList`, `Map` --> `HashMap` and so on). But type erasure is a real problem, making things ugly.

**Comment by benas** [comment]
Hi Stephan,

Here are my answers to your questions, using the same example given by @rishirane above:

* Which collection implementation to choose?

  - If the field type is an interface (`private Set<Account> accounts`), then as you said, the "default" implementation will be used, this is how I planned to implement it.
  - If the field is declared with a class type (`private HashSet<Account> accounts`), then of course, this type will be used (yes, there still people doing that, and jPopulator should expect it).

* How to infer the actual type when the field is a generic collection type?

  This is actually possible with reflection through the [ParametrizedType](http://docs.oracle.com/javase/7/docs/api/java/lang/reflect/ParameterizedType.html#getActualTypeArguments()) class.
This class allows to get the actual type of a generic collections at runtime.
I have implemented a show case of how to use this class [here](05b2739df41b11bb5b177d53803a4dd94489f41d), with some comments that I hope are clear.
In regards to how jPopulator should behave in this case:

  - If the field is a non-typed collection (`private Set accounts`), then jPopulator cannot know which type of objects to generate. Hence, it will generate an empty collection (as it does now).
  - If the field is a typed collection (`private set<Account> accounts`), then jPopulator can detect the actual type of the collection elements and will then generate instances of this type and fill the collection. 
This is what is planned to implement this feature.

I hope I've answered your questions :-)
Cheers
Mahmoud

**Comment by rishirane** [comment]
Hi Mahmoud;
Thanks for your reply. I did figured this approach and implemented it.
Hope you will add this feature soon.

Cheers

**Comment by benas** [comment]
Hi rishirane,

I'm glad that my reply was helpful :-)

I'll close the issue as soon as it is implemented.

Best regards,
Mahmoud

**Comment by stephanrauh** [comment]
Hi Mahmoud,

that's awesome! You found a way to beat type erasure. What a pity I didn't learn about it years ago, when I needed it...

Here's some background information why the approach works: http://stackoverflow.com/questions/923624/java-type-erasure-vs-fieldgetgenerictype-and-methodgetgenericreturntype

A la prochaine
Stephan

**Comment by benas** [comment]
Hi Stephan,

Cool! Thank you for the link. In fact it is a bit tricky :-)

I'm currently implementing this feature in version 1.2.0-SNAPSHOT. I'll keep you informed once the snapshot version is deployed to maven central repo to be able to test it.

Cheers
Mahmoud

**Comment by benas** [comment]
Hi @rishirane ,

Just a quick note, you can still populate the `Set<Account>` field using the `SetRandomizer`. This randomizer generates a random Set of elements that are generated using another randomizer: a delegate. Here is how to achieve this in your case:

```java
Randomizer<Account> accountRandomizer = new Randomizer<Account>() {

 private Populator p = new PopulatorBuilder().build();

    @Override
    public Account getRandomValue() {
       return p.populateBean(Account.class);
     }

};

Populator populator = new PopulatorBuilder()
       .registerRandomizer(TransactionDTO.class, Set.class, "accList", new SetRandomizer<Account>(accountRandomizer))
       .build();

TransactionDTO transactionDTO = populator.populateBean(TransactionDTO.class);
```

You should now have your accounts set populated with random instances of the `Account` class.
So it still possible with the current version but you should use a custom randomizer. You can also use a anonymous implementation directly when registering the randomizer instead of creating a separate class.

In the meanwhile, I continue implementing the feature in the next version. I'll keep you informed as soon as it is deployed in maven central repo.

Regards,
Mahmoud

**Comment by rishirane** [comment]
Hi Mahmoud

This is exactly I implemented on my project.

I have worked out a generic solution to this by checking Class Type and Generic Type to create List or Set. and sending sizes for each property in map.(ColoumnName and Size).

Good to hear, you are adding this feature in next version. That way we can use Jpopulator as it is.

Thanks. 
Hrishikesh Rane

**Comment by benas** [comment]
Hi Stephan, Hrishikesh,

After several tests, it turns out that it is *just* impossible to create instances of the parametrized type of a collection even though we are able to introspect its class at runtime, due to type erasure as Stephan said. Here is why:

The `java.lang.reflect.ParameterizedType` allows one to know at runtime the parametrized type of a field, as I showed in [this](https://github.com/benas/jPopulator/blob/master/src/test/java/io/github/benas/jpopulator/impl/PopulatorImplTest.java#L213) test case. But actually, at the end of introspection, we get the type of the object as `java.lang.reflect.Type` and not the actual type of the object. Let's quickly analyse the example:

```java
public class SocialPerson extends Person {
    private Set<Person> friends;
}
```

When jPopulator tries to populate the `friends` fields, it is able to know that it should generate instances of the `Person` class, but using the previous technique, it gets the following:

```java
Type[] actualTypeArguments = parameterizedType.getActualTypeArguments(); // parameterizedType = java.util.Set<io.github.benas.jpopulator.beans.Person>

// Get the actual type
Type actualTypeArgument = actualTypeArguments[0];// actualTypeArgument = Person.class
```

Ok good, at this point, we know that `actualTypeArgument` represents a `Person.class`, but its type is 
`java.lang.reflect.Type` and not `Person.class`, so when jPopulator calls `Class.newInstance();` on a `java.lang.reflect.Type`, It gets a:

`java.lang.IllegalAccessException: Can not call newInstance() on the Class for java.lang.Class`

Do you see the trick? Even though we are able to know the type of objects to generate, it is unfortunately impossible to do it at runtime..

In sum, populating a parametrized collection will still require the use of a custom populator (as shown in the previous comment with accountRandomizer, using the same "workaround" that Hrishikesh is using currently).

I'm looking forward for your feedback.

Cheers
Mahmoud

**Comment by stephanrauh** [comment]
Quel dommage! Your approach looked so promising! Can you get the qualified type name as a String and create the object via Class.forName().newInstance()?

Regards,
Stephan

**Comment by benas** [comment]
Hello,

Already tried with Class.forName() but it throws the same exception.. arrrgh :rage: !

**Comment by stephanrauh** [comment]
Hi Mahmoud,

I've tried your approach with Java 8 today, and it doesn't look bad. Since Java 8 ```Type``` contains a ```getType``` method, which maps to ```toString()``` by default. Using this method, I managed to build a  ```TrafficLightFactory``` producing a traffic light in a very abstract way:
```Java
import java.lang.reflect.Field;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;


public class TrafficLightFactory{
    public static void main(String[] args) throws ReflectiveOperationException {
        TrafficLight trafficLight = new TrafficLight();
        
        Field contentField = TrafficLight.class.getDeclaredField("lights");
        ParameterizedType arrayType = (ParameterizedType) contentField.getGenericType();
        
        String arrayClassName = arrayType.getRawType().getTypeName();
        Class arrayClass = Class.forName(arrayClassName);
        Object array = arrayClass.newInstance();
        contentField.set(trafficLight, array);
        
        Type[] contentTypes = arrayType.getActualTypeArguments();
        Type stringType = contentTypes[0];
        
        Class contentClass = Class.forName(stringType.getTypeName());
        Object arrayElement= contentClass.newInstance();
        
        ((List)array).add(arrayElement);
        
        System.out.println(arrayElement.toString());
    }

}

class TrafficLight {
    public ArrayList<Color> lights;
    
    @Override
    public String toString() {
        String visibleColors="";
        for (Color l: lights) {
            visibleColors+=l.toString() + "\r\n";
        }
        return visibleColors;
    }
}

class Color {
    String theColor;

    public Color() {
        theColor = "red";
    }

    public String toString() {
        return "The traffic light shows " + theColor+".";
    }
}
```

Now our abstract traffic light is red (like every semaphore that doesn't think too lowly of itself :) ).

Does this help you?

**Comment by benas** [comment]
Hi Stephan,

This is great! Your suggestion to use `Class.forName()` definitely helped me out. 
I've tried `Class.forName(actualTypeArgument.getClass().getName())` but this led to the same exception as I said in my previous comment.
 
I finally managed to get the class name based on the `toString()` method of the actual type pretty much like you do in your traffic light example, and it works! I have implemented this feature in a separate branch named `collection-population`. You can see [here](https://github.com/benas/jPopulator/blob/collection-population/src/main/java/io/github/benas/jpopulator/impl/PopulatorImpl.java#L320) that I can get the class name of the actual type and load it via `Class.forName()` as you suggested.

To test this feature, I used the following class:

```java
public class SocialPerson extends Person {

    private Set<Person> friends;

    private List<String> pseudos;

    private Map<String, String> accounts;
}
```

and the [test](https://github.com/benas/jPopulator/blob/collection-population/src/test/java/io/github/benas/jpopulator/impl/PopulatorImplTest.java#L158) is passing, all fields are populated with random values :-)

This means that we finally found a way to beat type erasure :wink:

The feature is almost done, I just wanna make sure all cases are taken into account and then I'll merge it in the master branch and do the release.

Many thanks to you for being involved to help out!

Best regards
Mahmoud

**Comment by stephanrauh** [comment]
Bonsoir Mahmoud,

always glad to help! BTW, the whole type erasure topic sounds like a good article for [BeyondJava.net](http://www.beyondjava.net). As far as I remember, you've got your own blog. But still, I'd like to invite you to write a guest article about type erasure and/or jPopulator. How do you like the idea?

Regards,
Stephan

**Comment by benas** [comment]
Sure! It would be great to share our little "adventure" with generics and type erasure on this use case with the community.

If you have an idea about the post content, do not hesitate to send me your thoughts by mail so we can discuss together.

I'm looking forward to collaborate with you :-)

**Comment by benas** [comment]
Hi @rishirane 

It took a while but populating collections is finally merged in the master branch and will be part of the next release. This feature has been added thanks to a great pull request by @feckertson , thank you Fred!

We've a test case for each interface and class of the Java collection framework:

- Arrays: https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/ArrayPopulationTest.java

- Collections: https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/CollectionPopulationTest.java

- Maps: https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/MapPopulationTest.java

Random Beans is now able to generate populated collections instead of empty ones.

May I ask you please to give it a try and keep me informed in case of any issue? You can [use](https://github.com/benas/random-beans#current-version) the current 2.0.0-SNAPSHOT version. It would be great to have your feedback!

Many thanks upfront
Kind regards
Mahmoud
