### ISSUE TITLE
Better support for randomizing beans with default values

### ISSUE THREAD

**Issue by petrholik** [benas/random-beans#218]
This is copy from https://github.com/benas/random-beans/issues/149#issuecomment-262849716
Hello I've recently facing issue: I've got DTO which assigns default values like this:

```
public CurrencyDTO(Long id) {
		this.id = id;
		this.finRefund = new BigDecimal(0);
		this.finSum = new BigDecimal(0);
}
```
It is not possible to properly randomize this object because there is:

`if (getFieldValue(result, field) != null)`
in populateField method.

I'll Implement it soon as PR.

Sincerely Petr Holik

**Comment by PascalSchumacher** [comment]
@petrholik Any updates on the pull request?

**Comment by petrholik** [comment]
Sorry about that, I was on vacation. Will do this weekend for sure!

**Comment by benas** [comment]
Hi @petrholik 

No problem, take your time.

I think your request is related to the `overrideDefaultInitialization` parameter.
We've added this parameter because we think Random Beans should not make the decision of randomizing fields that the class designer decided to set to a default value at construction time.

What is your plan for the `if (getFieldValue(result, field) != null)` condition?
I think if we remove it, the `finRefund` and `finSum` in your example will be randomized (I did'nt tried that) and the `overrideDefaultInitialization` will cover, not only inline initializations, but also those in constructors (which is better IMO).

Looking forward for your PR.

Many thanks upfront
Kind regards
Mahmoud

**Comment by PascalSchumacher** [comment]
Hi @petrholik

I just took a look at your example. Getting this to work will not be easy, because the values are initialized in a non-default constructor. Random-bean either uses the default constructor (if it exists) or uses objenesis to create an object. That means random-beans does not invoke any non-default (parametrized) constructors.

**Comment by petrholik** [comment]
Hello, 
i've experiencing some issues with getting project up and running. Its related to Lombok library, which does not work with Eclipse neon.2 for some reason. I'll figure it out tomorrow.

@PascalSchumacher @benas  At this time I am not sure how concrete will I implement it. But I am sure i'l will not change default behavior. I want to introduce possibility to override default behavior (which is IMO reasonable default). When I familiarize with code I am sure I'll find some way :)

**Comment by benas** [comment]
@petrholik 

Current version of random beans is able to generate a random instance of your `CurrencyDTO`:

<img width="716" alt="screen shot 2017-01-23 at 00 21 17" src="https://cloud.githubusercontent.com/assets/1210553/22187183/035f46ae-e102-11e6-9397-cd9fb9662379.png">

> It is not possible to properly randomize this object

What do you mean by "properly randomize this object" ?

**Comment by petrholik** [comment]
Hi @benas ,
It really looks that now it's working. When I tried, it does not work. Maybe it was resolved in someone other issue. I'll look more close this evening, and eventually close this issue.

Have a nice day

**Comment by benas** [comment]
Ok, no problem.

Please let us know if it's ok for you.

Kind regards
Mahmoud

**Comment by benas** [comment]
> It really looks that now it's working

It works, but it actually shouldn't!
See details in #228

**Comment by benas** [comment]
Hi Petr,

Have you been able to give it a second try?
If it works for you, please don't hesitate to close this issue.

FYI, as explained by @PascalSchumacher, any non default constructor will not be called.
Random Beans was designed to randomize Java beans, which should provide a default constructor by definition. Probably we need to add this detail in documentation.

Kind regards
Mahmoud

**Comment by petrholik** [comment]
Hello, 
sure I will. I am currently solving some big production issue. Hope i'll save some spare time in weekend.

Sincerely Petr

**Comment by petrholik** [comment]
Sorry for delay, 
I've test it and it has been fixed. It works as expected.

Have a nice Day
