### ISSUE TITLE
memoization, prevents that some objects's reaching their randomization depths that wanted

### ISSUE THREAD

**Issue by sunofkyuss** [benas/random-beans#236]
I will explain it with an example scenario:

```
public class A {
String name;
}

public class B {
List<A> soMuchA;
}

public class C {
B b;
A a;
}

main() {
EnhancedRandom.nextObject(C.class);
}
```

We assume that randomizationDepth is 3.
Now if soMuchA.size > = maxObjectPoolSize
a object that in C class will be populated by early populated beans but early populated ones were at 3rd depth so name variables that in A objects are null
then a.name will be null too. But name was at 3rd depth in this situation so it had to be populated.

I hope I could explain.

**Comment by PascalSchumacher** [comment]
Hi  @sunofkyuss,

thanks for reporting. :)

I'm probably misunderstanding you, but this example works for me:

``` java
public class A {
    String name;
}

public class B {
    List<A> soMuchA;
}

public class C {
    B b;
    A a;
}

@Test
public void test() {
    while(true) {
        C c = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
                .objectPoolSize(1).collectionSizeRange(10, 10).build()
                .nextObject(C.class);

        assertThat(c.b.soMuchA).hasSize(10);
        assertThat(c.a.name).isNotNull();
    }
}
```

**Comment by sunofkyuss** [comment]
Hi @PascalSchumacher,

you are welcome :)

Yes, I am usin 3.5.0.

This is okay with me but could you try with 3 randomization dept?

**Comment by PascalSchumacher** [comment]
Sorry, I missed the most important part (I should not post late at night when I'm tired, as that makes me look stupid). :(

This still works for me:

```java
@Test
public void test() {
    C c = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
            .objectPoolSize(1).randomizationDepth(3).collectionSizeRange(10, 10).build()
            .nextObject(C.class);

    assertThat(c.b.soMuchA).hasSize(10);
    assertThat(c.a.name).isNotNull();
}
```

**Comment by sunofkyuss** [comment]
I am sorry too. I made a mistake when figuring out the depth.
I said 3rd depth but I was wrong. name is at 2nd depth.

> C -> A -> name
> 0 -> 1 -> 2

So I hope this is the true one. Could you try with 2 randomization depth now :)

**Comment by PascalSchumacher** [comment]
Sure that fails, but I think that is unavoidable given object pooling.

At the moment you can just set a big enough `objectPoolSize` or a small enough `collectionSizeRange`.

@benas Maybe we should allow deactivating object pooling (e.g. by setting `objectPoolSize` to `0`)? What do you think?

**Comment by sunofkyuss** [comment]
> Edit: Setting objectPoolSize to Integer.MAX_VALUE effectivity disables it, so another option to disable it is unnecessary.

That doesnt work on my machine.

> java.lang.OutOfMemoryError: Requested array size exceeds VM limit

I think at least for now you can offer an option to deactivate pooling.

**Comment by benas** [comment]
@PascalSchumacher Thank you for the follow up. Setting objectPoolSize to Integer.MAX_VALUE makes  randomizing "recursive" types fail with OOM. (ex: `EnhancedRandomImplTest#generatedBeansShouldBeCorrectlyPopulated` or `EnhancedRandomImplTest#beansWithRecursiveStructureMustNotCauseStackOverflowException`). This is kind of expected since random beans will generate 2_147_483_647 instances of `Person` or `Node` before actually reusing a generated one.

Trying to disable object pooling will make random beans fail to populate such objects (regression on #44 and #74 ), so I'm not sure this is best way to proceed. ObjectPoolSize should be set by default to a reasonable value (probably 10 is not the best default value).

@sunofkyuss Thank you for reporting this. Please let us some time to analyse the problem in details.
We will let you know asap.

**Comment by sunofkyuss** [comment]
Thank you too @benas. You have all the time.

> Trying to disable object pooling will make random beans fail to populate such objects (regression on #44 and #74 ), so I'm not sure this is best way to proceed. ObjectPoolSize should be set by default to a reasonable value (probably 10 is not the best default value).

As far as I can see, depth limit can prevent recursion by only itself. So there would not be problem disabling pooling in this case.

**Comment by benas** [comment]
It took me a long debugging session but now I understand what's happening. Here is the starting point, a failing test with v3.5.0:

```java
public class A {
	String name;
}

public class B {
	List<A> soMuchA;
}

public class C {
	B b;
	A a;
}

public class Test {

    @org.junit.Test
    public void test() {
        C c = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
                .objectPoolSize(1)
                .randomizationDepth(2)
                .collectionSizeRange(3, 3)
                .build()
                .nextObject(C.class);

        assertThat(c.b.soMuchA).hasSize(3);
        assertThat(c.a.name).isNotNull();
    }
}
```

The short answer is: 

 * From the library user's point of view, this is a bug in random beans.
 * From the library developer's point of view, well, it depends :smile: (Please read the long answer to understand why)

The long answer is the following (RB stands for Random Beans):

1. RB starts randomizing C
2. RB creates an empty instance of C
3. RB looks for fields in C using reflection
4. Java Reflection API returns an array of fields in class C: [b,a]
5. RB picks the first field c.b and start randomizing it
6. RB looks for fields in class B using reflection
7. Java Reflection API returns an array of fields in class B: [soMuchA]
8. RB creates an empty list and start filling it with A instances
9. RB creates a first random instance of A. randomization depth is = 2, hence it does not populate the name field
10. RB repeats step 9 until the list is filled in (according to the specified collection size). In this step, RB will reuse the A instance generated in step 9 since objectPoolSize = 1
11. RB picks the next field in C, c.a, and start randomizing it
12. RB looks in its cash if already randomized type A. Yes, so it sets c.a to the instance of A created in step 9 (with name null)

The "problem" is in step 4. Java Reflection API [says](https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getDeclaredFields()) there is no particular order in which fields are returned. But looks like there are some JVMs that always return fields in their declaration order.
Surprizingly, if I change the order of fields in C class like this:

```java
public class C {
	A a;
	B b;
}
```

the test passes! And it makes sense. If RB starts with randomizing field c.a before c.b, then c.a.name will be randomized and then c.b.soMuchA will be filled in with correclty randomized A instances ("correclty" means randomized to the specified randomization depth, ie with name field populated).

So depending on which order the Java Reflection API returns fields, the combination of objectPoolSize/randomizationDepth might work or not.
You see now why I said it depends? :wink:

There is one possible solution to this problem. We can add some sort of intelligence on what field to randomize first.
In this case, when randomizing C, we get an array of fields [b,a] or [a,b]. We could statically figure out that to populate B, we need to populate A first. So RB should start with c.a, not c.b (regardless the order in which the JVM returns fields).

This is some how like the reactor of maven. Maven is able to figure out which module depends on which other module and start building sibling modules first. Implementing this kind of requirement in RB would be interesting, but not that easy IMHO.

When I first started working on random beans, I've never ever thought that creating a random instance of a Java object would be full of challenges!!

**Comment by benas** [comment]
@sunofkyuss The case you reported is definitely valid and thank you for reporting it! But it still an edge case: We need to have a specific type hierarchy and a specific parameters combination to make it happens. Do you agree? 

In hindsight, the amount of work needed to address such a particular case in the implementation of random beans if far greater than its added value. In such cases, I suggest helping random beans with a custom randomizer or, as suggested by Pascal, setting the objectPoolSize to a big enough value or the collectionSizeRange to a small enough value.

What do you think?

**Comment by sunofkyuss** [comment]
@benas I cannot think an easy way to solve this problem for now. So I guess I agree.

Actually, tweaking these parameters works for my situation too  and I can get used to it :) .

Thank you for your interest and effort.

**Comment by benas** [comment]
Ok, thank you for your time.
