### ISSUE TITLE
Object generation is too slow

### ISSUE THREAD

**Issue by shaleenmishra** [benas/random-beans#257]
Thanks for providing the library. Keep up the good work.
However, on my first attempt of using it, i found it very slow. Took about 10 seconds to build a simple object. Is it supposed to be that slow?

` EnhancedRandomBuilder enhancedRandomBuilder = EnhancedRandomBuilder.aNewEnhancedRandomBuilder();
 long t1 = System.currentTimeMillis();
 SomeClass someClass= enhancedRandomBuilder.build().nextObject(SomeClass .class);
 System.out.println(System.currentTimeMillis()-t1);
`

random beans version version: 2.0.0
project jdk version: 1.7x

**Comment by johnou** [comment]
@shaleenmishra check your entropy, probably low, thread dump of the JVM should also confirm if that's the issue.

**Comment by shaleenmishra** [comment]
Entropy on my system shows 800+, which i believe is a healthy number. What else could it be? I will also try to take JVM's thread dump.

**Comment by PascalSchumacher** [comment]
10 seconds for a simple object seems far from normal.

Randombeans can be slow if you have a deep object graph with many collections containing other collections.

Try reducing `objectPoolSize` (default generates 100 objects per type, before they are reused) or `randomizationDepth` (default10), see  https://github.com/benas/random-beans/wiki/Randomization-parameters for details.

**Comment by PascalSchumacher** [comment]
@shaleenmishra Sorry I missed that you use `2.0.0`, not sure which configuration parameters were available back then (a lot less than with the current version `3.6.0`).

**Comment by benas** [comment]
Oh damn 10 seconds, I can prepare a coffee in that time!

That's not normal of course, but I can't give you any more details without having the base type to randomize.

Have you tried to use v3.6.0 ? I remember we fixed some performance problems since v2 and introduced a couple of parameters that may improve ramdomization speed (as suggested by @PascalSchumacher ).

Please let us know if you have the same issue with v3.6.
