### ISSUE TITLE
Constructor of innerclass is not executed

### ISSUE THREAD

**Issue by axelsegers** [benas/random-beans#268]
I just noticed that constructors of inner-classes are not executed.
My parent class has the following code

private List<ABC> list;

....and the inner class

public class ABC{
   public ABC(){
    //some code here which is not executed
  }
}

Using random-beans the list property is populated as well as the properties of the innerclass ABC. However the constructor of ABC is never executed which blocks me because some important initialisation is there....

**Comment by benas** [comment]
I'm not sure I fully understand what are you expecting.

If the list is populated and the properties of ABC are also populated, then random beans has done its work right? Are you expecting RB to call the constructor of ABC?

it would be great If you can provide a test with what is expected. Many thanks upfront

**Comment by axelsegers** [comment]
Yes i'm expecting that RB calls the constructor of ABC, which is not happening.

**Comment by benas** [comment]
I do confirm, the constructor of the inner class is not called. However, if you declare `ABC` as static, then the constructor should be called.

This is because `Class.getDeclaredConstructor()` throws a `NoSuchMethodException` when the inner class is not static and RB falls back to objenesis in this case which by-passes the constructor.

Can you try making `ABC` as static and let me know if it works fro you?

**Comment by benas** [comment]
> Can you try making `ABC` as static and let me know if it works fro you?

@axelsegers Have you got a chance to test this?

I'm re-reading this thread and based on the previous comments, I believe RB can't do anything in this case. If making the class static works for you, then this is the way to work around the issue. If it is not possible to change the class (may be legacy type you can't change), then I will close the issue and add a note about it in the [know limitations](https://github.com/benas/random-beans/wiki/known-limitations) section.

Looking forward for your feedback. Thank you upfront.

**Comment by benas** [comment]
Summing up on this. For inner classes, `Class.getDeclaredConstructor()` throws an exception. For static nested classes, it does not throw this exception. Here is an example:

```java
import org.objenesis.Objenesis;
import org.objenesis.ObjenesisStd;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;

public class TestInnerClass {

    public class ABC {
        public ABC() {
            System.out.println("ABC.ABC");
        }
    }

    public static class DEF {
        public DEF() {
            System.out.println("DEF.DEF");
        }
    }

    public static void main(String[] args) {
        try {
            Constructor<ABC> constructor = ABC.class.getDeclaredConstructor();
            constructor.newInstance();
        } catch (NoSuchMethodException | IllegalAccessException | InstantiationException | InvocationTargetException e) {
            e.printStackTrace();
            System.err.println("falling back to objenesis for ABC");
            Objenesis objenesis = new ObjenesisStd();
            objenesis.newInstance(ABC.class);
        }

        System.out.println("#####");

        try {
            Constructor<DEF> constructor = DEF.class.getDeclaredConstructor();
            constructor.newInstance();
        } catch (NoSuchMethodException | IllegalAccessException | InstantiationException | InvocationTargetException e) {
            e.printStackTrace();
            System.err.println("falling back to objenesis for DEF");
            Objenesis objenesis = new ObjenesisStd();
            objenesis.newInstance(DEF.class);
        }
    }
}
```

Which prints:

```
java.lang.NoSuchMethodException: io.github.benas.randombeans.beans.TestInnerClass$ABC.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2554)
	at io.github.benas.randombeans.beans.TestInnerClass.main(TestInnerClass.java:48)
falling back to objenesis for ABC
#####
DEF.DEF
```

> Yes i'm expecting that RB calls the constructor of ABC, which is not happening.

For inner classes, Random Beans will fall back to using Objenesis (mostly as shown in the previous example) which will create the instance *without calling the constructor* (See [Javadoc of `Objenesis#newInstance(Class)`](http://objenesis.org/apidocs/org/objenesis/Objenesis.html#newInstance-java.lang.Class-). And that's why the constructor of the inner class is not called.

As said previously, I'm not sure RB can do something to overcome this, So I added a section about this limitation in the [known limitations](https://github.com/benas/random-beans/wiki/known-limitations#inner-classes-and-static-nested-classes) page.

@axelsegers Thank you anyway for opening this issue!
