### ISSUE TITLE
Support for meta annotations

### ISSUE THREAD

**Issue by reitzmichnicht** [benas/random-beans#285]
Hi

Using random-beans 3.7.0 I spotted some problems with the random-beans-validator module.
This module only scans for the annotations itself, not for meta-annotations.
For example hibernate-validator contains a `@NotEmpty `annotation which in turn has a `@Size ` annotation.
This can be solved by recursion of annotations in the BeanValidationRandomizerRegistry, see Junit5 AnnotationSupport.isAnnotated() method for an example.

Not sure how to implement this without copying a lot of junit code.

Kind regards,
Michael

**Comment by benas** [comment]
Hi Michael,

Valid point! Thank you for opening this issue.

I will try to make RB support meta annotations.
I'm not sure this will get released in a minor version, so I'm planning it for v4.

Kr
Mahmoud

**Comment by benas** [comment]
> Not sure how to implement this without copying a lot of junit code.

That's not my first order concern, my concern is rather how to implement this on RB side. Let's imagine we manage to introspect the meta-annotation, the question is how to combine all criteria from subsequent annotations. To take the example of [`@NotNull`](https://github.com/hibernate/hibernate-validator/blob/master/engine/src/main/java/org/hibernate/validator/constraints/NotEmpty.java) from hibernate validator, it brings `@NotNull` and `@Size(min = 1)`. I wonder how to combine two (or more) randomizers to generate a random value according to this composite contract.

I've been thinking about how to tackle this, but I struggle to find a simple way to achieve it. Any idea is welcome. What do you think?

Otherwise, I will add this to the [know limitations](https://github.com/benas/random-beans/wiki/known-limitations) section of the docs and close this issue.

BTW, I noticed that RB does not support `@NotEmpty`, so I created a feature request for that (#339).

**Comment by benas** [comment]
I was working on this issue the last few days and I still don't see an easy way to combine randomizers (in a generic way). Moreover, I took a look at JUnit 5 `AnnotationSupport.isAnnotated()` and I'm not ready to do something similar in here..

It is always possible to register a custom randomizer (that delegates to other randomizers) for a field annotated with the meta-annotation using `FieldDefinitionBuilder#isAnnotatedWith`.

For these reasons, I added a note about this in the [known limitations](https://github.com/benas/random-beans/wiki/known-limitations#bean-validation) section and I'm closing this issue for now.

@reitzmichnicht Thank you for this feature request anyway!
