### ISSUE TITLE
Supports XML-based bean validation

### ISSUE THREAD

**Issue by cfollet** [benas/random-beans#294]
I would like to know if random-beans supports XML-based bean validation.
I saw that annotation-based bean is supported, is there a way to achieve it using XML?

It's more like a support/feature-request issue, not a bug

**Comment by benas** [comment]
I'm not sure how we can achieve this. Can you provide/suggest an example of how to configure random beans to support XML based bean validation?

**Comment by benas** [comment]
Any news on this?

**Comment by cfollet** [comment]
I just wanted to know if it's actually doable. It seems that it's not, right? 
I will try to provide an example later. It doesn't look impossible to achieve — both XML and annotation based validation are the results of the same JSR. What do you think?

**Comment by ilyas-keser** [comment]
I just tried random beans. The idea is nice but is it planned to support constraints like:

    @Email
    private String email;

Email is an annotation from javax.validation.constraints.*.

**Comment by PascalSchumacher** [comment]
@ilyas-keser The `random-beans-validation` module supports bean validation, see: https://github.com/benas/random-beans/wiki/bean-validation-support

**Comment by benas** [comment]
According to [Hibernate Validator docs](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#chapter-xml-configuration), enabling bean validation through XML requires adding a `validation.xml` under `META-INF` to bootstrap the bean validation provider and another file containing constraints in XML (similar to annotations) under `META-INF/validation/`. I tested this in branch [issue-294](https://github.com/benas/random-beans/commit/967319e4cabee1a31442fa391c96d2215ed66f4e).

My concern is that in order to generate a valid instance, let's say of a `Person` type,  RB should do the work of looking for a `META-INF/validation.xml` and then `META-INF/validation/person-validation.xml` (we can imagine a naming convention like `Person.class -> person-validation.xml`), then parse the file and deduce contraints.. That's obviously a lot of work and I'm not even sure it is the role of RB. Bean validation support via annotation was straightforward using a custom registry that introspects annotations at runtime. However, with XML, it is another story..

@cfollet Wdyt?

**Comment by benas** [comment]
I'm closing this issue for the concern explained in my previous comment: I can't imagine RB doing the work of parsing the bean validation XML file and deducing constraints in order to generate random values according to these constraints.

I will remove the branch `issue-294`, but I'm joining the test case I used as patch file here if anyone is interested: [issue-294.txt](https://github.com/benas/random-beans/files/2833647/issue-294.txt).

I'm open to discussion if there is another way to do it.
