### ISSUE TITLE
Repeatable and Seed option

### ISSUE THREAD

**Issue by Toilal** [benas/random-beans#30]
In some case, it may be usefull to generate multiple objects with the same data.

```java
Populator populator = PopulatorBuilder.repeatable(true).build();

Bean1 = populator.populateBean(BeanA.class);
Bean2 = populator.populateBean(BeanA.class);
// Bean1.equals(Bean2) == true
```

Also, it's often handy to have always the same bean data constructed for each unit tests runs. It could be done by adding a seed option to make generation of data stable between multiple JVM relaunch ...

```java
Populator populator = PopulatorBuilder.seed(65487322L).build();

Bean1 = populator.populateBean(BeanA.class);
// Bean1.getLabel() == "ABCD"

// Restart the JVM
Populator populator = PopulatorBuilder.seed(65487322L).build();

Bean1 = populator.populateBean(BeanA.class);
// Bean1.getLabel() == "ABCD" => Same value on each run.
```

If a new property is added to `BeanA.class`, or an existing property is removed, properties should keep the same values as before. (=> so underlying Random object can't be a singleton anymore)

**Comment by benas** [comment]
Hi again :-)

* In regards to the repeatable parameter

This is pretty easy to implement (using some kind of caching). But what are the use cases for generating the same instance?

* In regards to adding a seed

This is quite interesting option because jPopulator (by nature generating random data each time) is not stable across multiple runs. The seed option is an elegant solution and should be a priority for next release!

Regards
Mahmoud

**Comment by Toilal** [comment]
Hi,

I also contribute to [javabean-tester](https://github.com/hazendaz/javabean-tester) which is a library to perform basic tests on Java Beans, like setter and getter consistency, hashCode & equals.

My final idea is to use jPopulator as the data generator for javabean-tester, and then check that 2 instances generated with `repeatable(true)` have the same hashCode and equals OK. But maybe the seed option is sufficient.

I'll have some spare time next week, so I'll open pull requests about issues I have previously opened.

**Comment by benas** [comment]
Hello Rémi,

I have added the seed option as requested. Currently, random beans is able to generate the same objects for the same seed, here is an [example](https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/EnhancedRandomImplTest.java#L215).

Thank you for requesting this feature, this is really interesting to be able to have stable random data across JVM restarts.

As discussed, the `repeatable` option may be redundant once we have a fixed seed.

Looking forward for your feedback in order to include this feature in the upcoming release.

Kind regards
Mahmoud

**Comment by PascalSchumacher** [comment]
I guess after: https://github.com/benas/random-beans/commit/da0b73c4d60d1ffbf0886db073f854ab6cb76eed this should be closed?

**Comment by benas** [comment]
Yes, I am updating the documentation and will review all issues to generate the release notes.

The seed option seems to be working fine, if there is any issue, it will be fixed in the next release.
