### ISSUE TITLE
how to limit recursive children bean's depth, please help~

### ISSUE THREAD

**Issue by live106** [benas/random-beans#312]
the bean like this:
```
public class Data {
    private List<Data> datas;
    //...
}
```

**Comment by benas** [comment]
You can use a combination of [objectPoolSize](https://github.com/benas/random-beans/wiki/Randomization-parameters#object-pool-size) and [randomizationDepth](https://github.com/benas/random-beans/wiki/Randomization-parameters#randomization-depth) parameters in order to avoid recursion in data structures like these.

**Comment by live106** [comment]
Thanks for your response. In fact, I've read the doc and tried that, but failed, I'll try it again, check if I miss sth. @benas

**Comment by benas** [comment]
I'm closing this ticket as I think there is no issue, a combination of `objectPoolSize` and `randomizationDepth` parameters should do it.

@live106 if you still struggle to implement what you want, feel free to add a comment here.
