### ISSUE TITLE
Make generics propagate down the generation tree

### ISSUE THREAD

**Issue by kivan-mih** [benas/random-beans#313]
Consider I have classes:
```
class A {
   B<String> b;
}

class B<C>{
   C c;
}
```

For field A.b runtime information about generic type String exists, however it is not propagated down when B instance is generated, thus it limits generation possibilities of random-beans for many scenarios. To solve this problem generic type information should be propagated down the generation tree.

**Comment by benas** [comment]
Even though some generic info can be retrieved at runtime (I tried to do it on something similar [here](https://github.com/benas/random-beans/issues/242#issuecomment-441480572)), I don't think random beans should do it. It looks simple with two classes like in your example, but the implementation should consider all types in the object graph, keeping a handle to generic types, and trying to propagate down the subtypes and fields, etc.. This will make the code base complex for no real added value.

I prefer waiting for reified generic where I would imagine being able to do something like `Field.isGenericType()` and then if true do `Field.getActualType()` (same thing for a class) rather than a hacky complex solution that fights type erasure.

The [Known limitations](https://github.com/benas/random-beans/wiki/known-limitations) section of the wiki explains this issue and I'm not planning to introduce such a feature for now.

In all cases, you can register a custom randomizer for that field according to your needs.

Does this make sense?

**Comment by benas** [comment]
@kivan-mih I'm closing this issue for now as explained in my previous comment. If you have any comment/feedback, please feel free to add it here.
