### ISSUE TITLE
Failing to use jPopulator with lombok.

### ISSUE THREAD

**Issue by jsmirnov** [benas/random-beans#42]
Hi,

In my project I am using lombok, to hide all boilerplate part of the code. I am trying to use jPopulator, but for some reason I am getting following error message:

`java.lang.NoSuchMethodException: Property '***' has no setter method in class ***`

Might be I am doing something wrong? Or these libraries currently can't be used together atm?

P.S. My problem is described here as well: https://stackoverflow.com/questions/34038236/how-to-make-benas-jpopulator-work-with-lombok

**Comment by MAMABA** [comment]
Hello,

I think that private field without a setter cannot have a value with jPopulator... Have you tried to use jPopulator after compiling your class with lombok? 

Regards,

**Comment by jsmirnov** [comment]
@MAMABA 
Hello,
You are right the field is private with no setter.
But I am not sure why on runtime populator doesn't see any setter, while on previous lines I am using  setters/getters generated by lombok.

**Comment by jsmirnov** [comment]
@MAMABA 
It seems that I found something:
while in master version field is set as accessble:
https://github.com/benas/jPopulator/blob/master/jpopulator-core/src/main/java/io/github/benas/jpopulator/impl/PopulatorImpl.java#L260
in 1.2.0 tag field is set via `org.apache.commons.beanutils.PropertyUtils` which will fail if there is no accessor method.

I'll try master version

**Comment by jsmirnov** [comment]
It seems that there is no normal way to include master version through maven. So I am confused a little bit.

**Comment by MAMABA** [comment]
I remembre that someone has requested this feature....
I propose you to package and install the master via maven and include it into your POM to do a test.

**Comment by benas** [comment]
Hi @jsmirnov 

Thank you for pointing out this issue.
There is no reason jPopulator may not work with lombok.

jPopulator is intended to populate standard Java Beans (with default constructor, getters and setters), see the note [here](https://github.com/benas/jPopulator/wiki/Key-APIs).

It uses apache commons beanutils behind the scene to set random values to fields. `PropertyUtils` complains when there is no setter for the field, and this is fine with what jPopulator was designed for.

To use the snapshot version, you'll need to declare the sonatype snamshot repository:

```xml
<repository>
    <id>ossrh</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
</repository>
```

and include the snapshot version in your pom. I'll update the documentation with these instructions.
But the problem is, I'm not sure I pushed the last version to central repo.. shame on me :flushed: I'll do it asap.

That said, I'll try to reproduce your use case using lombok and keep you informed.

Kind regards,
Mahmoud

@MAMABA Thank you for your replies!

**Comment by jsmirnov** [comment]
@benas 
What would be snapshot version exactly? 1.3.0-SNAPSHOT? :confused:

**Comment by jsmirnov** [comment]
@benas 
Could you push the latest snapshot

**Comment by frankowskid** [comment]
@ jsmirnov 
PropertyUtils was replace with setProperty to allow to initiate immutable object where by definition there are no setters.
Additionally Objenesis library was used to create objects in case, default constructor does not exist or is not accessible.

**Comment by jsmirnov** [comment]
@frankowskid 
Well stil i'd like to try with snapshot, might be this will work. On another side I'd really don't understand why jPopulator doesn't work with lombok.

**Comment by benas** [comment]
Hi,

I just deployed the 1.3.0-SNAPSHOT to maven central:
https://oss.sonatype.org/content/repositories/snapshots/io/github/benas/jpopulator-core/

Sorry for being late, I was behind a nasty firewall/proxy at work today :rage:

Cheers
Mahmoud

**Comment by frankowskid** [comment]
@jsmirnov 

Could you share a bean which causing a trouble? I wrote a quick test with bean as below, and it seems to work with both, PropertyUtils.setProperty(...) and current implementation of setProperty().

@Data
public class ObjectWithLombok {
//    @Getter
//    @Setter
    private String value;
}

    @Test 
    public void testObjectWithLombok() throws IllegalAccessException, NoSuchMethodException, InvocationTargetException {
        final ObjectWithLombok immutableBean = populator.populateBean(ObjectWithLombok.class);
        assertThat(immutableBean.getValue()).isNotNull();
    }

**Comment by jsmirnov** [comment]
@frankowskid 
yes sure. I stripped some stuff but basically it looks like this:
```
....

@Entity
@Accessors(chain = true)
public class Tour extends UniversallyUniqueIdentity {
    @Getter
    @Setter
    @JsonView(TourView.Summary.class)
    private Integer capacityInPersons;
.....

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tour)) return false;
        Tour tour = (Tour) o;
        return Objects.equals(getId(), tour.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

```

**Comment by jsmirnov** [comment]
@frankowskid @MAMABA @benas 
It seems that the problem is neither with lombok, nor with jPopulator.
I mean this seems an issue with JPA related stuff.

**Comment by jsmirnov** [comment]
@MAMABA @benas @frankowskid 

It seems I'v found an issue - `@Accessors(chain = true)` seems to be it.
Not sure for reasoning.

**Comment by frankowskid** [comment]
@jsmirnov @MAMABA @benas 
It is not a lombok issue. It seems to be an issue of chain setter. Below class fails test.
```java
public class ObjectWithLombok {
    private String value;

    public String getValue() {
        return value;
    }

    public String setValue(String value) {
        this.value = value;
        return value;
    }
```

It seems to be a BeanUtils issue, which implements Java Bean specification.
The section "7.1 Accessor methods" states that getter/setter must be:
> For simple properties the accessor type signatures are:
> void setFoo(PropertyType value); // simple setter
> PropertyType getFoo();           // simple getter

So chain setter does not fit into this specification.

See also:
http://stackoverflow.com/questions/22743765/beanutils-not-works-for-chain-setter

**Comment by benas** [comment]
Hi,

Same here, I've tried to populate a Java Bean annotated with lombok and it is working fine with jPopulator.

@frankowskid Great analysis, in fact `@Accessors(chain = true)` generates fluent getters and setters which are not compliant with Java Bean standard definition. That's why `PropertyUtils.setProperty` does not find the standard setter.

This issue is clearly explained here: [http://zeroturnaround.com/rebellabs/a-fluent-api-or-not-a-fluent-api-that-is-the-question/](http://zeroturnaround.com/rebellabs/a-fluent-api-or-not-a-fluent-api-that-is-the-question/), see "Being fluent: where and why? > The Java Bean" section.

Since jPopulator is intended to populate **standard** Java Beans (as mentioned in the documentation), I guess this issue is caused by a misuse of the library.

Kind regards
Mahmoud
